In [1]:
import numpy as np
import sklearn
from sklearn import preprocessing

In [2]:
data = np.array([[3.2, -3.0, 8.9],
                [-8.6, 7.6, 3.7],
                [6.2, -5.6, 5.6],
                [1.3, 4.1, -3.3]])

In [3]:
binarized_data = preprocessing.Binarizer(threshold = 0.5).transform(data)
print("nBinarized data:n", binarized_data)

nBinarized data:n [[1. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]


In [4]:
Mean = [ 0.525   ,    0.775    ,  3.725 ]
Std_deviation = [ 5.55039413 , 5.303949 , 4.4622724 ]

In [5]:
data_scaled = preprocessing.scale(data)
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis = 0))

Mean = [-1.38777878e-17 -2.77555756e-17 -5.55111512e-17]
Std deviation = [1. 1. 1.]


In [6]:
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled_minmax = data_scaler_minmax.fit_transform(data)
print ("nMin max scaled data:n", data_scaled_minmax)

nMin max scaled data:n [[0.7972973  0.1969697  1.        ]
 [0.         1.         0.57377049]
 [1.         0.         0.7295082 ]
 [0.66891892 0.73484848 0.        ]]


In [7]:
## L1 Normalisations (# the sum of the absolute values is always up to 1 in each row)

In [8]:
# Normalize data
l1_normalized_data = preprocessing.normalize(data, norm = 'l1')
print("nL1 normalized data:n", l1_normalized_data)

nL1 normalized data:n [[ 0.21192053 -0.1986755   0.58940397]
 [-0.4321608   0.38190955  0.18592965]
 [ 0.35632184 -0.32183908  0.32183908]
 [ 0.14942529  0.47126437 -0.37931034]]


In [9]:
## L2 Normalisation (# the sum of the squares is always up to 1 in each row.)

In [10]:
# Normalize data
l2_normalized_data = preprocessing.normalize(data, norm = 'l2')
print("nL2 normalized data:n", l2_normalized_data)

nL2 normalized data:n [[ 0.32250921 -0.30235238  0.89697873]
 [-0.71318354  0.63025523  0.30683478]
 [ 0.61643499 -0.55677999  0.55677999]
 [ 0.2397969   0.75628252 -0.6087152 ]]


In [11]:
##Labelling of DATA !!

In [12]:
# Sample input labels
i_labels = ['orange','white','purple','maroon','blue','florocent','black']

In [13]:
# Creating the label encoder
enc = preprocessing.LabelEncoder()
enc.fit(i_labels)

LabelEncoder()

In [14]:
label_encoder = preprocessing.LabelEncoder()

In [15]:
# encoding a set of labels
t_labels = ['yellow','green','white']
enc_values = label_encoder.fit_transform(t_labels)
print("nLabels =", t_labels)

nLabels = ['yellow', 'green', 'white']


In [16]:
print("Encoded values =", list(enc_values))

Encoded values = [2, 0, 1]


In [43]:
# decoding a set of values
enc_values = [2,0,1]
dec_list = label_encoder.inverse_transform(enc_values)
print("nEncoded values =", dec_list)

nEncoded values = ['yellow' 'green' 'white']


In [17]:
##Step for building a Classifier in python !!

In [19]:
import sklearn

In [20]:
from sklearn.datasets import load_breast_cancer

In [21]:
data = load_breast_cancer()

In [23]:
type(data)

sklearn.utils.Bunch

In [24]:
l_names = data['target_names']
labels = data['target']
f_names = data['feature_names']
features = data['data']

In [25]:
print(l_names)

['malignant' 'benign']


In [26]:
print(labels[0])
0

0


0

In [27]:
print(f_names[0])

mean radius


In [30]:
print(features[0])

[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
 1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
 6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
 1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
 4.601e-01 1.189e-01]


In [31]:
print(features[1])

[2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
 7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
 5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
 2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
 2.750e-01 8.902e-02]


In [32]:
##splitting the data!

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
train, test, train_labels, test_labels = train_test_split(features,labels,test_size = 0.40, random_state = 42)


In [35]:
##building model !

In [36]:
from sklearn.naive_bayes import GaussianNB


In [37]:
gnb = GaussianNB()

In [38]:
model = gnb.fit(train, train_labels)

In [39]:
pred = gnb.predict(test)
print(pred)

[1 0 0 1 1 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 1 1 1 0 0 1 1 0 0 1 0
 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0
 1 1 0 0 0 1 1 1 0 0 1 1 0 1 0 0 1 1 0 0 0 1 1 1 0 1 1 0 0 1 0 1 1 0 1 0 0
 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 0
 0 1 1 0 1 0 1 1 1 1 0 1 1 0 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1
 0 0 1 1 0 1]


In [42]:
from sklearn.metrics import accuracy_score
print(accuracy_score(test_labels,pred))


0.9517543859649122


In [43]:
##Support vector machines !!

In [44]:
import pandas as pd
import numpy as np
from sklearn import svm, datasets
import matplotlib.pyplot as plt

In [45]:
iris_data = datasets.load_iris()

In [46]:
X = iris_data.data[:, :2]
y = iris_data.target