# Question 1:

Write a program that calculates and prints the value according to the given formula:

Q = Square root of [(2 * C * D)/H]

Following are the fixed values of C and H:

C is 50. H is 30.

D is the variable whose values should be input to your program in a comma-separated sequence.

Example

Let us assume the following comma separated input sequence is given to the program:

100,150,180

The output of the program should be:

18,22,24


In [7]:
import math
c = 50 #given
h = 30 #given
print("Take the input of D \n")
l = ()
l = input()
m = l.split(',')
g = []
for i in m :
    g.append(int(i))
g

new = []
for i in g:
    new.append(math.floor(math.sqrt((2*c*i)/h)))
    
a,b,c = new
print(a ,",", b , ",",c)




Take the input of D 

100,150,180
18 , 22 , 24


# Question 2:
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.

Note: i=0,1.., X-1; j=0,1,¡¬Y-1.

Example

Suppose the following inputs are given to the program:

3,5

Then, the output of the program should be:

[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]] 


In [8]:
import numpy as np

In [12]:
row = 3
column = 5

In [13]:
temp = np.random.randn(row,column)

In [14]:
temp

array([[ 0.48126813, -0.55343205,  1.1288732 ,  0.7953269 , -0.45157099],
       [-0.45536507,  1.02621128,  1.04133831, -0.8839073 , -1.07352822],
       [-0.87335349,  0.25889435, -0.92412533, -0.22164602, -0.14001787]])

In [15]:
type(temp)

numpy.ndarray

In [16]:
for i in range(0,row):
    for j in range(0,column):
        temp[i][j] = i*j

In [17]:
temp

array([[0., 0., 0., 0., 0.],
       [0., 1., 2., 3., 4.],
       [0., 2., 4., 6., 8.]])

In [18]:
for i in temp :
    print(i)

[0. 0. 0. 0. 0.]
[0. 1. 2. 3. 4.]
[0. 2. 4. 6. 8.]


# Question 3:
Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.

Suppose the following input is supplied to the program:

without,hello,bag,world

Then, the output should be:

bag,hello,without,world


In [23]:
l = ()
l = input()
l
type(l)
m = l.split(",")
m.sort()
a,b,c,d = m
print(a,",",b,",",c,",",d)

without,hello,bag,world
bag , hello , without , world


# Question 4:
Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.

Suppose the following input is supplied to the program:

hello world and practice makes perfect and hello world again

Then, the output should be:

again and hello makes perfect practice world


In [66]:
l = ()
l = input()
l.split(" ")
m = l.split()
s = set(m)
t = tuple(s)
temp = []
for i in t:
    temp.append(i)
temp.sort()
for i in temp :
    print(i ,end=" ")






hello world and practice makes perfect and hello world again
again and hello makes perfect practice world 

# Question 5:
Write a program that accepts a sentence and calculate the number of letters and digits.

Suppose the following input is supplied to the program:

hello world! 123

Then, the output should be:

LETTERS 10

DIGITS 3


In [67]:
s = "hello world! 123"
letters = 0
digits = 0
for i in range(0,len(s)):
    if s[i].isalpha() == True :
        letters = letters + 1
    elif s[i].isalnum() == True:
        digits = digits + 1
    else :
        continue
else :
    print("LETTERS" , letters)
    print("DIGITS" , digits)


LETTERS 10
DIGITS 3


# Question 6:
A website requires the users to input username and password to register. Write a program to check the validity of password input by users.

Following are the criteria for checking the password:

1. At least 1 letter between [a-z]

2. At least 1 number between [0-9]

1. At least 1 letter between [A-Z]

3. At least 1 character from [$#@]

4. Minimum length of transaction password: 6

5. Maximum length of transaction password: 12

Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma.

Example

If the following passwords are given as input to the program:

ABd1234@1,a F1#,2w3E*,2We3345

Then, the output of the program should be:

ABd1234@1


In [70]:
s = ()
s = input("enter the input as the format given in Question above !")
s.split(",")
m = s.split(",")
for i in m: 
    temp = str(i)
    temp1 = []
    for j in temp:
        temp1.append(j)
    else:
        lowercase = 0
        uppercase = 0
        numeric = 0
        specialchr = 0
        for k in temp1:
            if k.isalpha() == True :
                if k.islower() == True :
                    lowercase = lowercase + 1
                elif k.isupper() == True :
                    uppercase = uppercase + 1
            elif  k.isnumeric() == True :
                numeric = numeric + 1
            else :
                specialchr = specialchr +1
        else:
            if lowercase>=1 and uppercase>=1 and numeric>=1 and specialchr>=1 and len(temp1) >= 6:
                
                print("The output of the program is \n" , i)


    
    


enter the input as the format given in Question above !ABd1234@1,a F1#,2w3E*,2We3345
The output of the program is 
 ABd1234@1
