# 1.	Write a Python Program to Add Two Matrices?

In [2]:
# Program to add two matrices using nested loop

X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]


result = [[0,0,0],
        [0,0,0],
        [0,0,0]]

# iterate through rows
for i in range(len(X)):
# iterate through columns
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]

for r in result:
    print(r)


[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


# 2.	Write a Python Program to Multiply Two Matrices?

In [3]:
import pandas as pd

In [4]:
import numpy as np

In [6]:
temp = np.array([[1,3],[4,5]])

In [7]:
temp

array([[1, 3],
       [4, 5]])

In [8]:
np.matrix(temp)

matrix([[1, 3],
        [4, 5]])

In [9]:
matrix1 = np.matrix(temp)

In [10]:
## similary taking another matrix , we get !

In [11]:
temp1 = np.array([[5,7],[9,7]])

In [12]:
temp1

array([[5, 7],
       [9, 7]])

In [13]:
np.matrix(temp1)

matrix([[5, 7],
        [9, 7]])

In [15]:
matrix2 = np.matrix(temp1)

In [16]:
matrix2

matrix([[5, 7],
        [9, 7]])

In [17]:
matrix1

matrix([[1, 3],
        [4, 5]])

In [18]:
matrix1 @ matrix2

matrix([[32, 28],
        [65, 63]])

# 3.	Write a Python Program to Transpose a Matrix?

In [23]:
def Transpose(matrix):
    return matrix.T

In [24]:
Transpose(matrix1)

matrix([[1, 4],
        [3, 5]])

In [25]:
matrix2

matrix([[5, 7],
        [9, 7]])

In [26]:
##After transpose !

In [27]:
Transpose(matrix2)

matrix([[5, 9],
        [7, 7]])

# 4.	Write a Python Program to Sort Words in Alphabetic Order?

In [28]:
my_str = "Hello This is Aryan doing inueron assignment"

In [29]:
words = [word.lower() for word in my_str.split(" ")]

In [30]:
words

['hello', 'this', 'is', 'aryan', 'doing', 'inueron', 'assignment']

In [31]:
words.sort()

In [32]:
print("The sorted words are :")
for word in words:
    print(word)

The sorted words are :
aryan
assignment
doing
hello
inueron
is
this


# 5.	Write a Python Program to Remove Punctuation From a String?

In [33]:
# define punctuation
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

my_str = "Hello!!!, he said ---and went."

# To take input from the user
# my_str = input("Enter a string: ")

# remove punctuation from the string
no_punct = ""
for char in my_str:
   if char not in punctuations:
       no_punct = no_punct + char

# display the unpunctuated string
print(no_punct)


Hello he said and went
